#!/usr/bin/env php
<?php

/*
 * This file is part of the c2is/silex-bootstrap.
 *
 * (c) Morgan Brunot <brunot.morgan@gmail.com>
 */

set_time_limit(0);

require_once __DIR__.'/vendor/autoload.php';
require_once __DIR__.'/src/bootstrap.php';

$console = $app['console'];

use Core\Command\Tests\UnitsCommand as TestsUnitsCommand;
use Core\Command\Migration\UpCommand as MigrationUpCommand;
use Core\Command\Migration\DownCommand as MigrationDownCommand;
use Core\Command\Migration\GenerateCommand as MigrationGenerateCommand;
use Core\Command\Clear\CacheCommand as ClearCacheCommand;

$console->add(new TestsUnitsCommand());
$console->add(new MigrationUpCommand());
$console->add(new MigrationDownCommand());
$console->add(new MigrationGenerateCommand());
$console->add(new ClearCacheCommand());

$console->run();
